[package]
name = "data-plane"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
crypto = { path = "../crypto" }
domain = { path = "../domain" }

thiserror = "2.0.21"
tokio = { version = "1.53.1", features = ["io-util", "net"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "io-util", "net"] }
